name: Tests

on: [push, pull_request]

jobs:
  test:
    permissions: write-all
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.0.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --json --outputFile=jest.results.json

      - name: Jest GitHub Action
        uses: willcaul/jest-github-action@v1.0.2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
            
